// ── The verified tools database (the moat) ─────────────────────────────
// Every row is hand-verified. Only rows with `verified: true` are ever
// recommended. Free-tier numbers drift each quarter — `last_verified_at`
// is the mechanism that keeps this honest, shown publicly with a
// "report outdated" button.
//
// This file is the living part of the product. To update a fact: edit the
// row and bump `last_verified_at`. Nothing else in the app hard-codes tool data.

import type { Tool } from "./types";

const V = "2026-09-04"; // last verification pass for this seed

export const TOOLS: Tool[] = [
  // ─────────────────────────── PAYMENTS (accept from customers) ───────────
  {
    id: "stripe",
    name: "Stripe",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "No monthly fee — per-transaction pricing only",
    free_ends_at: "~2.9% + fixed fee per charge",
    requires_card: false,
    countries_blocked: ["PK", "BD", "NG"],
    countries_supported: ["*"],
    gotcha:
      "Merchant accounts are not available in Pakistan, Bangladesh or Nigeria.",
    docs_url: "https://stripe.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 3,
    payment_intents: ["accept-from-customers", "subscriptions"],
  },
  {
    id: "paypal",
    name: "PayPal",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "No setup fee — per-transaction pricing",
    free_ends_at: "~3.5% + fixed fee per charge",
    requires_card: false,
    countries_blocked: ["PK"],
    countries_supported: ["*"],
    gotcha:
      "Merchant/receiving support is limited or unavailable in many countries — verify for yours.",
    docs_url: "https://developer.paypal.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 6,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "paddle",
    name: "Paddle",
    category: "payments",
    tags: ["payments-web"],
    platform: ["web"],
    pricing_model: "revenue-share",
    free_type: "ongoing",
    free_details:
      "No monthly fee — Merchant of Record, handles global VAT/tax for you",
    free_ends_at: "~5% + $0.50 revenue share per sale",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://developer.paddle.com",
    verified: true,
    last_verified_at: V,
    rank: 1,
    payment_intents: ["accept-from-customers", "subscriptions"],
  },
  {
    id: "lemonsqueezy",
    name: "Lemon Squeezy",
    category: "payments",
    tags: ["payments-web"],
    platform: ["web"],
    pricing_model: "revenue-share",
    free_type: "ongoing",
    free_details: "No monthly fee — Merchant of Record, handles global VAT/tax",
    free_ends_at: "~5% + $0.50 per sale",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://docs.lemonsqueezy.com",
    verified: true,
    last_verified_at: V,
    rank: 2,
    payment_intents: ["accept-from-customers", "subscriptions"],
  },
  {
    id: "revenuecat",
    name: "RevenueCat",
    category: "payments",
    tags: ["payments-mobile"],
    platform: ["mobile"],
    pricing_model: "revenue-share",
    free_type: "ongoing",
    free_details: "Free under $2,500/mo tracked revenue",
    free_ends_at: "then 1% of gross revenue",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "The 1% is on gross revenue and stacks on top of Apple/Google's 15–30% cut.",
    docs_url: "https://www.revenuecat.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
    payment_intents: ["subscriptions", "accept-from-customers"],
  },
  {
    id: "razorpay",
    name: "Razorpay",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "No setup fee — India's primary gateway",
    free_ends_at: "~2% per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["IN"],
    gotcha: null,
    docs_url: "https://razorpay.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
    payment_intents: ["accept-from-customers", "subscriptions"],
  },
  {
    id: "cashfree",
    name: "Cashfree",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "No setup fee — India local gateway",
    free_ends_at: "~1.75%+ per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["IN"],
    gotcha: null,
    docs_url: "https://docs.cashfree.com",
    verified: true,
    last_verified_at: V,
    rank: 2,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "payu",
    name: "PayU",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "No setup fee — India local gateway",
    free_ends_at: "~2% per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["IN"],
    gotcha: null,
    docs_url: "https://docs.payu.in",
    verified: true,
    last_verified_at: V,
    rank: 3,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "paytm",
    name: "Paytm",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "No setup fee — India local gateway + wallet",
    free_ends_at: "~2% per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["IN"],
    gotcha: null,
    docs_url: "https://business.paytm.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 4,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "payfast",
    name: "PayFast (PK)",
    category: "payments",
    tags: ["payments-web"],
    platform: ["web"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "No/low setup fee — Pakistan local gateway",
    free_ends_at: "per-transaction fee",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["PK"],
    gotcha: null,
    docs_url: "https://payfast.pk",
    verified: true,
    last_verified_at: V,
    rank: 3,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "safepay",
    name: "Safepay",
    category: "payments",
    tags: ["payments-web"],
    platform: ["web"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "Low setup — Pakistan local card gateway",
    free_ends_at: "per-transaction fee",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["PK"],
    gotcha: null,
    docs_url: "https://getsafepay.com",
    verified: true,
    last_verified_at: V,
    rank: 4,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "xpay",
    name: "XPay (PK)",
    category: "payments",
    tags: ["payments-web"],
    platform: ["web"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "Low setup — Pakistan local gateway",
    free_ends_at: "per-transaction fee",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["PK"],
    gotcha: null,
    docs_url: "https://xpay.pk",
    verified: true,
    last_verified_at: V,
    rank: 5,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "jazzcash",
    name: "JazzCash",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "Merchant fees only — Pakistan mobile wallet API",
    free_ends_at: "merchant fee per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["PK"],
    gotcha:
      "Local wallet — best for domestic PKR collections, not international cards.",
    docs_url: "https://developer.jazzcash.com.pk",
    verified: true,
    last_verified_at: V,
    rank: 6,
    is_local_only: true,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "easypaisa",
    name: "Easypaisa",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "Merchant fees only — Pakistan mobile wallet API",
    free_ends_at: "merchant fee per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["PK"],
    gotcha: "Local wallet — domestic PKR only.",
    docs_url: "https://easypaisa.com.pk",
    verified: true,
    last_verified_at: V,
    rank: 7,
    is_local_only: true,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "sslcommerz",
    name: "SSLCommerz",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details:
      "Setup fee, no monthly — 1 API covers cards + bKash/Nagad/Rocket",
    free_ends_at: "per-transaction fee",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["BD"],
    gotcha: null,
    docs_url: "https://developer.sslcommerz.com",
    verified: true,
    last_verified_at: V,
    rank: 1,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "bkash",
    name: "bKash",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "Bangladesh mobile wallet",
    free_ends_at: "~1.5–2% per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["BD"],
    gotcha: "Local wallet — domestic BDT only.",
    docs_url: "https://developer.bka.sh",
    verified: true,
    last_verified_at: V,
    rank: 2,
    is_local_only: true,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "nagad",
    name: "Nagad",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "Bangladesh mobile wallet",
    free_ends_at: "~1.5–2% per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["BD"],
    gotcha: "Local wallet — domestic BDT only.",
    docs_url: "https://nagad.com.bd",
    verified: true,
    last_verified_at: V,
    rank: 3,
    is_local_only: true,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "aamarpay",
    name: "AamarPay",
    category: "payments",
    tags: ["payments-web"],
    platform: ["web"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "Low setup — Bangladesh local gateway",
    free_ends_at: "per-transaction fee",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["BD"],
    gotcha: null,
    docs_url: "https://aamarpay.com",
    verified: true,
    last_verified_at: V,
    rank: 4,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "shurjopay",
    name: "ShurjoPay",
    category: "payments",
    tags: ["payments-web"],
    platform: ["web"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "Low setup — Bangladesh local gateway",
    free_ends_at: "per-transaction fee",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["BD"],
    gotcha: null,
    docs_url: "https://shurjopay.com.bd",
    verified: true,
    last_verified_at: V,
    rank: 5,
    payment_intents: ["accept-from-customers"],
  },
  {
    id: "paystack",
    name: "Paystack",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "No setup fee — Nigeria's primary gateway",
    free_ends_at: "~1.5% + fixed fee per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["NG"],
    gotcha: null,
    docs_url: "https://paystack.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
    payment_intents: ["accept-from-customers", "subscriptions"],
  },
  {
    id: "flutterwave",
    name: "Flutterwave",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "per-transaction",
    free_type: "ongoing",
    free_details: "No setup fee — pan-African gateway",
    free_ends_at: "~1.4%+ per transaction",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["NG"],
    gotcha: null,
    docs_url: "https://developer.flutterwave.com",
    verified: true,
    last_verified_at: V,
    rank: 2,
    payment_intents: ["accept-from-customers", "subscriptions"],
  },

  // ─────────────────────────── PAYMENTS (receive your own income) ─────────
  {
    id: "payoneer",
    name: "Payoneer",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "conversion-fee",
    free_type: "ongoing",
    free_details: "Best for Upwork/Fiverr payouts",
    free_ends_at: "~2.5–3% conversion",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "For receiving your own income — not a checkout gateway for customers.",
    docs_url: "https://www.payoneer.com",
    verified: true,
    last_verified_at: V,
    rank: 1,
    payment_intents: ["receive-own-income"],
  },
  {
    id: "wise",
    name: "Wise",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "conversion-fee",
    free_type: "ongoing",
    free_details: "Cheapest for direct-client transfers",
    free_ends_at: "often <1% conversion",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: "For receiving your own income — not a customer checkout.",
    docs_url: "https://wise.com",
    verified: true,
    last_verified_at: V,
    rank: 2,
    payment_intents: ["receive-own-income"],
  },
  {
    id: "sadapay",
    name: "SadaPay",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "account",
    free_type: "ongoing",
    free_details: "Local PKR account for freelancers",
    free_ends_at: "low local fees",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["PK"],
    gotcha: "Local PKR receiving account, pairs with Payoneer/Wise.",
    docs_url: "https://sadapay.pk",
    verified: true,
    last_verified_at: V,
    rank: 3,
    is_local_only: true,
    payment_intents: ["receive-own-income"],
  },
  {
    id: "nayapay",
    name: "NayaPay",
    category: "payments",
    tags: ["payments-web", "payments-mobile"],
    platform: ["web", "mobile"],
    pricing_model: "account",
    free_type: "ongoing",
    free_details: "Local PKR account for freelancers",
    free_ends_at: "low local fees",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["PK"],
    gotcha: "Local PKR receiving account, pairs with Payoneer/Wise.",
    docs_url: "https://nayapay.com",
    verified: true,
    last_verified_at: V,
    rank: 4,
    is_local_only: true,
    payment_intents: ["receive-own-income"],
  },

  // ─────────────────────────── AI / LLM ──────────────────────────────────
  {
    id: "google-ai-studio",
    name: "Google AI Studio (Gemini Flash)",
    category: "ai-llm",
    tags: ["llm-chat"],
    platform: ["web", "mobile"],
    pricing_model: "per-token",
    free_type: "ongoing",
    free_details: "Flash: ~1,500 req/day, ~15/min, no expiry — no card",
    free_ends_at: "pay-as-you-go beyond free tier",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Flash only (Pro is paid). Free inputs may train Google's models — don't send sensitive data.",
    docs_url: "https://ai.google.dev/gemini-api/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },
  {
    id: "groq",
    name: "Groq",
    category: "ai-llm",
    tags: ["llm-chat"],
    platform: ["web", "mobile"],
    pricing_model: "per-token",
    free_type: "ongoing",
    free_details: "~1,000 req/day per model, fastest inference — no card",
    free_ends_at: "pay-as-you-go beyond free tier",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://console.groq.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    category: "ai-llm",
    tags: ["llm-chat"],
    platform: ["web", "mobile"],
    pricing_model: "per-token",
    free_type: "ongoing",
    free_details:
      "One API, many models — free model variants available, no card",
    free_ends_at: "pay per model beyond free variants",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://openrouter.ai/docs",
    verified: true,
    last_verified_at: V,
    rank: 3,
  },
  {
    id: "mistral",
    name: "Mistral (& SambaNova)",
    category: "ai-llm",
    tags: ["llm-chat"],
    platform: ["web", "mobile"],
    pricing_model: "per-token",
    free_type: "ongoing",
    free_details:
      "Open-weight models, free tier, no card — cheap production option",
    free_ends_at: "pay-as-you-go beyond free tier",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://docs.mistral.ai",
    verified: true,
    last_verified_at: V,
    rank: 4,
  },
  {
    id: "openai",
    name: "OpenAI",
    category: "ai-llm",
    tags: ["llm-chat"],
    platform: ["web", "mobile"],
    pricing_model: "per-token",
    free_type: "trial",
    free_details: "~$5 sign-up credit (rarely offered now)",
    free_ends_at: "pay-as-you-go",
    requires_card: true,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Requires a card. Use GPT-4o-mini for cheap/simple tasks, not the flagship model.",
    docs_url: "https://platform.openai.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 5,
  },
  {
    id: "anthropic",
    name: "Anthropic (Claude)",
    category: "ai-llm",
    tags: ["llm-chat"],
    platform: ["web", "mobile"],
    pricing_model: "per-token",
    free_type: "trial",
    free_details: "~$5 sign-up credit",
    free_ends_at: "pay-as-you-go",
    requires_card: true,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Higher cost/token — reserve for hard reasoning, long context or coding, not simple classification.",
    docs_url: "https://docs.anthropic.com",
    verified: true,
    last_verified_at: V,
    rank: 6,
  },
  {
    id: "huggingface-llm",
    name: "Hugging Face Inference",
    category: "ai-llm",
    tags: ["llm-chat"],
    platform: ["web", "mobile"],
    pricing_model: "per-request",
    free_type: "none",
    free_details: "Hosted open models, only ~$0.10/mo of free inference",
    free_ends_at: "pay per request — very low volume only",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: "Effectively no meaningful free tier for real traffic.",
    docs_url: "https://huggingface.co/docs/api-inference",
    verified: true,
    last_verified_at: V,
    rank: 7,
  },

  // ─────────────────────────── SPEECH-TO-TEXT ────────────────────────────
  {
    id: "assemblyai",
    name: "AssemblyAI",
    category: "speech",
    tags: ["speech-to-text"],
    not_for: ["real-time-under-100ms"],
    platform: ["web", "mobile"],
    pricing_model: "per-minute",
    free_type: "credits",
    free_details:
      "$50 credit, no expiry (~185h prerecorded / 333h streaming); free = 5 streams/min",
    free_ends_at: "then ~$0.15/hr",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://www.assemblyai.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },
  {
    id: "deepgram",
    name: "Deepgram",
    category: "speech",
    tags: ["speech-to-text"],
    platform: ["web", "mobile"],
    pricing_model: "per-minute",
    free_type: "credits",
    free_details: "$200 credit on signup, real-time capable — no card",
    free_ends_at: "then pay-as-you-go",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://developers.deepgram.com",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },
  {
    id: "whisper",
    name: "OpenAI Whisper (self-host)",
    category: "speech",
    tags: ["speech-to-text"],
    platform: ["web", "mobile"],
    pricing_model: "self-host",
    free_type: "none",
    free_details:
      "Free & open-source, but there is no hosted free tier — you self-host the compute",
    free_ends_at: "your own server/GPU cost",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: "No hosted API — you run and pay for the infrastructure yourself.",
    docs_url: "https://github.com/openai/whisper",
    verified: true,
    last_verified_at: V,
    rank: 3,
  },

  // ─────────────────────────── TEXT-TO-SPEECH ────────────────────────────
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    category: "speech",
    tags: ["text-to-speech"],
    platform: ["web", "mobile"],
    pricing_model: "per-character",
    free_type: "ongoing",
    free_details: "Free tier, no card — text-to-speech + voice cloning",
    free_ends_at: "paid tiers for higher volume",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://elevenlabs.io/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },

  // ─────────────────────────── IMAGE / VIDEO ─────────────────────────────
  {
    id: "stability",
    name: "Stability AI",
    category: "image",
    tags: ["image-gen"],
    platform: ["web", "mobile"],
    pricing_model: "per-image",
    free_type: "credits",
    free_details: "25 free credits on Google signup (one-time)",
    free_ends_at: "no ongoing free quota after — pay per image",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: "One-time credits only — there's no monthly free allowance.",
    docs_url: "https://platform.stability.ai/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },
  {
    id: "replicate",
    name: "Replicate",
    category: "image",
    tags: ["image-gen", "video-gen"],
    platform: ["web", "mobile"],
    pricing_model: "per-second",
    free_type: "credits",
    free_details: "Limited trial credits — huge model catalog via one API",
    free_ends_at: "bills per GPU-second after",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: "20–60s cold starts that you also pay for.",
    docs_url: "https://replicate.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },
  {
    id: "fal",
    name: "Fal.ai",
    category: "image",
    tags: ["image-gen", "video-gen"],
    platform: ["web", "mobile"],
    pricing_model: "per-image",
    free_type: "trial",
    free_details: "One-time signup credits, fastest inference / best DX",
    free_ends_at: "~$0.025–0.05/image, no ongoing free tier",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: "No ongoing free tier — signup credits only.",
    docs_url: "https://docs.fal.ai",
    verified: true,
    last_verified_at: V,
    rank: 3,
  },
  {
    id: "huggingface-image",
    name: "Hugging Face Inference (image)",
    category: "image",
    tags: ["image-gen"],
    platform: ["web", "mobile"],
    pricing_model: "per-request",
    free_type: "none",
    free_details: "Open image models, ~$0.10/mo of free inference",
    free_ends_at: "pay per request — low volume only",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: "No meaningful free tier for real traffic.",
    docs_url: "https://huggingface.co/docs/api-inference",
    verified: true,
    last_verified_at: V,
    rank: 4,
  },
  {
    id: "gemini-imagen",
    name: "Google Gemini (Imagen)",
    category: "image",
    tags: ["image-gen"],
    platform: ["web", "mobile"],
    pricing_model: "per-image",
    free_type: "none",
    free_details: "Image generation sits in the paid rows of the free tier",
    free_ends_at: "paid per image — check exact model ID for free status",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: "Imagen rows are paid-only even on the otherwise-free Gemini tier.",
    docs_url: "https://ai.google.dev/gemini-api/docs/imagen",
    verified: true,
    last_verified_at: V,
    rank: 5,
  },

  // ─────────────────────────── DATABASE ──────────────────────────────────
  {
    id: "supabase",
    name: "Supabase (Postgres)",
    category: "database",
    tags: ["database"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details:
      "2 projects, 500MB DB, 1GB files, 5GB egress, 50k MAU, 500k edge calls",
    free_ends_at: "$25/mo Pro when you outgrow it",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Projects auto-pause after 7 days idle — plan the $25/mo upgrade before an always-on launch.",
    docs_url: "https://supabase.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },
  {
    id: "neon",
    name: "Neon (Serverless Postgres)",
    category: "database",
    tags: ["database"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "Serverless Postgres, branching, scales to zero",
    free_ends_at: "usage-based paid tiers",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://neon.tech/docs",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },
  {
    id: "firebase-firestore",
    name: "Firebase (Firestore)",
    category: "database",
    tags: ["database"],
    platform: ["web", "mobile"],
    pricing_model: "per-operation",
    free_type: "ongoing",
    free_details: "Generous Spark plan — NoSQL in the Google stack",
    free_ends_at: "bills per read/write on Blaze",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: "Bills per read/write — costs can spike with chatty apps.",
    docs_url: "https://firebase.google.com/docs/firestore",
    verified: true,
    last_verified_at: V,
    rank: 3,
  },
  {
    id: "mongodb-atlas",
    name: "MongoDB Atlas",
    category: "database",
    tags: ["database"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "Free 512MB shared cluster — NoSQL",
    free_ends_at: "paid dedicated clusters",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://www.mongodb.com/docs/atlas",
    verified: true,
    last_verified_at: V,
    rank: 4,
  },

  // ─────────────────────────── AUTH ──────────────────────────────────────
  {
    id: "clerk",
    name: "Clerk",
    category: "auth",
    tags: ["auth"],
    platform: ["web", "mobile"],
    pricing_model: "per-mau",
    free_type: "ongoing",
    free_details:
      "50,000 MRU free (raised from 10k on Feb 5 2026) — drop-in auth with prebuilt UI",
    free_ends_at: "Pro from $25/mo, then ~$0.02 per MRU beyond 50k",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Bills monthly retained users (MRU) — a narrower unit than the MAU other providers meter.",
    docs_url: "https://clerk.com/docs",
    verified: true,
    last_verified_at: "2026-09-12",
    rank: 1,
  },
  {
    id: "firebase-auth",
    name: "Firebase Auth",
    category: "auth",
    tags: ["auth"],
    platform: ["web", "mobile"],
    pricing_model: "free",
    free_type: "ongoing",
    free_details: "Free and generous — Google stack",
    free_ends_at: "phone-auth and some features metered",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://firebase.google.com/docs/auth",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },
  {
    id: "auth0",
    name: "Auth0",
    category: "auth",
    tags: ["auth"],
    platform: ["web", "mobile"],
    pricing_model: "per-mau",
    free_type: "ongoing",
    free_details: "Free up to ~25k MAU — enterprise-grade",
    free_ends_at: "paid tiers beyond free MAU",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://auth0.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 3,
  },
  {
    id: "supabase-auth",
    name: "Supabase Auth",
    category: "auth",
    tags: ["auth"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "50k MAU, bundled with Supabase DB/storage/realtime",
    free_ends_at: "part of the $25/mo Supabase Pro upgrade",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Part of a Supabase project — the project pauses after 7 days idle on the free tier.",
    docs_url: "https://supabase.com/docs/guides/auth",
    verified: true,
    last_verified_at: V,
    rank: 4,
  },

  // ─────────────────────────── HOSTING ───────────────────────────────────
  {
    id: "cloudflare-pages",
    name: "Cloudflare Pages / Workers",
    category: "hosting",
    tags: ["hosting"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details:
      "Generous free tier — edge apps + static, no commercial restriction",
    free_ends_at: "$5/mo Workers paid for higher limits",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://developers.cloudflare.com/pages",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },
  {
    id: "netlify",
    name: "Netlify",
    category: "hosting",
    tags: ["hosting"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "Free tier — static / Jamstack",
    free_ends_at: "paid tiers for bandwidth/build minutes",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://docs.netlify.com",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },
  {
    id: "vercel",
    name: "Vercel",
    category: "hosting",
    tags: ["hosting"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "Hobby tier free — best-in-class for Next.js / frontend",
    free_ends_at: "$20/mo Pro for commercial use",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Hobby tier is non-commercial — you'll need Pro once the app makes money.",
    docs_url: "https://vercel.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 3,
  },
  {
    id: "render",
    name: "Render",
    category: "hosting",
    tags: ["hosting", "background-jobs"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "Free tier for backend + cron jobs",
    free_ends_at: "paid instances for always-on",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Free instances spin down when idle (cold starts on first request).",
    docs_url: "https://render.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 4,
  },
  {
    id: "railway",
    name: "Railway",
    category: "hosting",
    tags: ["hosting", "background-jobs"],
    platform: ["web", "mobile"],
    pricing_model: "usage",
    free_type: "trial",
    free_details: "Trial credit for a full backend + workers",
    free_ends_at: "usage-based billing after the credit",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://docs.railway.app",
    verified: true,
    last_verified_at: V,
    rank: 5,
  },

  // ─────────────────────────── FILE STORAGE ──────────────────────────────
  {
    id: "cloudflare-r2",
    name: "Cloudflare R2",
    category: "storage",
    tags: ["file-storage"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "Free tier with NO egress fees (big win vs S3)",
    free_ends_at: "$0.015/GB storage beyond free",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://developers.cloudflare.com/r2",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },
  {
    id: "backblaze-b2",
    name: "Backblaze B2",
    category: "storage",
    tags: ["file-storage"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "10GB free — cheap object storage",
    free_ends_at: "$6/TB/mo beyond free",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://www.backblaze.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },
  {
    id: "supabase-storage",
    name: "Supabase Storage",
    category: "storage",
    tags: ["file-storage"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "1GB, bundled with the Supabase project",
    free_ends_at: "part of the $25/mo Supabase Pro upgrade",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Part of a Supabase project — pauses after 7 days idle on the free tier.",
    docs_url: "https://supabase.com/docs/guides/storage",
    verified: true,
    last_verified_at: V,
    rank: 3,
  },
  {
    id: "aws-s3",
    name: "AWS S3",
    category: "storage",
    tags: ["file-storage"],
    platform: ["web", "mobile"],
    pricing_model: "usage",
    free_type: "trial",
    free_details: "5GB free — but only for the first 12 months",
    free_ends_at: "then pay for storage + egress",
    requires_card: true,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Free tier expires after 12 months, and egress fees add up. Requires a card.",
    docs_url: "https://docs.aws.amazon.com/s3",
    verified: true,
    last_verified_at: V,
    rank: 4,
  },

  // ─────────────────────────── EMAIL ─────────────────────────────────────
  {
    id: "resend",
    name: "Resend",
    category: "email",
    tags: ["email"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details:
      "~3,000/mo, 100/day free — developer-first transactional email",
    free_ends_at: "$20/mo for higher volume",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://resend.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },
  {
    id: "onesignal-email",
    name: "OneSignal Email",
    category: "email",
    tags: ["email"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "10,000/mo free — email + push in one platform",
    free_ends_at: "paid tiers for higher volume",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://documentation.onesignal.com",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },
  {
    id: "sendgrid",
    name: "SendGrid",
    category: "email",
    tags: ["email"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "trial",
    free_details:
      "100/day for 60 days only — the permanent free plan was retired May 27, 2025",
    free_ends_at: "must upgrade to a paid plan ($19.95/mo+) after 60 days",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "No longer an ongoing free tier — new signups get a 60-day trial, then a forced upgrade.",
    docs_url: "https://docs.sendgrid.com",
    verified: true,
    last_verified_at: "2026-09-12",
    rank: 4,
  },

  // ─────────────────────────── PUSH NOTIFICATIONS ────────────────────────
  {
    id: "fcm",
    name: "Firebase Cloud Messaging (FCM)",
    category: "push",
    tags: ["push-notifications"],
    platform: ["web", "mobile"],
    pricing_model: "free",
    free_type: "ongoing",
    free_details: "Fully free, unlimited — mobile + web push",
    free_ends_at: "always free",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Free but bare-bones — you build your own segmentation/targeting logic.",
    docs_url: "https://firebase.google.com/docs/cloud-messaging",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },
  {
    id: "onesignal-push",
    name: "OneSignal",
    category: "push",
    tags: ["push-notifications"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "Web push + 10k emails free, managed journeys",
    free_ends_at: "Growth $19/mo + $0.012/MAU",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Mobile push now capped at 1,000 MAU (new accts Sep 1 2026, existing Oct 1 2026), then paid.",
    docs_url: "https://documentation.onesignal.com",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },

  // ─────────────────────────── REALTIME ──────────────────────────────────
  {
    id: "ably",
    name: "Ably",
    category: "realtime",
    tags: ["realtime"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "6M messages/mo free — realtime messaging",
    free_ends_at: "paid tiers beyond free messages",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://ably.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 1,
  },
  {
    id: "pusher",
    name: "Pusher",
    category: "realtime",
    tags: ["realtime"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "200k messages/day, 100 concurrent connections free",
    free_ends_at: "paid tiers for more connections",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha: null,
    docs_url: "https://pusher.com/docs",
    verified: true,
    last_verified_at: V,
    rank: 2,
  },
  {
    id: "supabase-realtime",
    name: "Supabase Realtime",
    category: "realtime",
    tags: ["realtime"],
    platform: ["web", "mobile"],
    pricing_model: "tiered",
    free_type: "ongoing",
    free_details: "200 concurrent conns, 2M msgs/mo, bundled with Supabase",
    free_ends_at: "part of the $25/mo Supabase Pro upgrade",
    requires_card: false,
    countries_blocked: [],
    countries_supported: ["*"],
    gotcha:
      "Part of a Supabase project — pauses after 7 days idle on the free tier.",
    docs_url: "https://supabase.com/docs/guides/realtime",
    verified: true,
    last_verified_at: V,
    rank: 3,
  },
];

// ── Country-fallback map (the regional core) ───────────────────────────
// Encodes the payment reality per country: which global gateways are blocked,
// and the ordered fallback list to promote — by platform lane where it matters.
export interface CountryRule {
  name: string;
  stripe: boolean; // is Stripe available for merchants here?
  paypal_merchant: boolean;
  fallbacks: {
    web?: string[];
    mobile?: string[];
    local?: string[];
    all?: string[]; // used when the same list serves every lane
  };
  // Whether to warn that we're assuming global availability (unknown/other).
  assume_global?: boolean;
}

export const COUNTRY_RULES: Record<string, CountryRule> = {
  PK: {
    name: "Pakistan",
    stripe: false,
    paypal_merchant: false,
    fallbacks: {
      web: ["paddle", "lemonsqueezy", "payfast", "safepay"],
      mobile: ["revenuecat"],
      local: ["jazzcash", "easypaisa"],
    },
  },
  IN: {
    name: "India",
    stripe: true,
    paypal_merchant: true,
    fallbacks: {
      all: ["razorpay", "cashfree", "payu", "paytm"],
    },
  },
  BD: {
    name: "Bangladesh",
    stripe: false,
    paypal_merchant: false,
    fallbacks: {
      all: ["sslcommerz", "bkash", "nagad", "aamarpay", "shurjopay"],
    },
  },
  NG: {
    name: "Nigeria",
    stripe: false,
    paypal_merchant: false,
    fallbacks: {
      all: ["paystack", "flutterwave"],
    },
  },
  other: {
    name: "your region",
    stripe: true,
    paypal_merchant: true,
    fallbacks: {
      web: ["paddle", "lemonsqueezy"],
      mobile: ["revenuecat"],
    },
    assume_global: true,
  },
  unknown: {
    name: "your region",
    stripe: true,
    paypal_merchant: true,
    fallbacks: {
      web: ["paddle", "lemonsqueezy"],
      mobile: ["revenuecat"],
    },
    assume_global: true,
  },
};

// Fast lookup by id.
export const TOOLS_BY_ID: Record<string, Tool> = Object.fromEntries(
  TOOLS.map((t) => [t.id, t]),
);
